### ISSUE TITLE
爬起点的书名报错

### ISSUE THREAD

**Issue by HuanYuanHe** [howie6879/owllook#100]
请问下大佬，开起点爬虫时候报错
AttributeError: 'Response' object has no attribute 'html'
这个是什么情况呢

**Comment by HuanYuanHe** [comment]
太折磨了  写java的  整了几天这个py的项目 玩不来o(╥﹏╥)o

**Comment by howie6879** [comment]
你限制下ruia框架的版本，比如版本等于0.5.8

**Comment by HuanYuanHe** [comment]
![image](https://user-images.githubusercontent.com/51042672/104831611-91a14900-58c5-11eb-9050-23acf1998262.png)
我去翻了大佬介绍ruia的项目  用这个语法解决了
