### ISSUE TITLE
加入书架问题

### ISSUE THREAD

**Issue by VimT** [howie6879/owllook#14]
加入书架按钮从源码上来看是
```html
<p>状    态：连载中,
  <a href="javascript:;" onclick="addBookCase(43995);" rel="nofollow">加入书架</a>,
  <a href="#footer">直达底部</a>
</p>
```

而 这个 `href="javascript:;"` 在浏览器（chrome, firefox）中均被解析为```http://www.owllook.net/owllook_content?url=http://www.23txt.com/javascript:;&name=...```打开了一个新页面，而没有触发 addBookCase 函数

改成 `href="javascript:void(0)"` 应该就ok了:smile:

**Comment by howie6879** [comment]
目录解析页面 这个加入书架是无效的。下次我把他过滤掉
