### ISSUE TITLE
docker Internal Server Error

### ISSUE THREAD

**Issue by vinwang** [howie6879/owllook#18]
用docker创建执行之后，http://127.0.0.1:8001/ 报错Internal Server Error，这是什么原因，刚接触python。

**Comment by howie6879** [comment]
有详细的日志信息么

**Comment by vinwang** [comment]
@howie6879 是因为无法连接到docker mongo 容器，直接127.0.0.1:27017是无法连接的，端口是对的。

**Comment by howie6879** [comment]
那你只用把ip开放出来就好了

**Comment by howie6879** [comment]
那你只用把ip开放出来就好了

**Comment by vinwang** [comment]
能详细说一下吗？谢谢

**Comment by howie6879** [comment]
开放你的mongo的ip 相当于连接一个远程一样
