### ISSUE TITLE
小说章节列表页加入书架按钮没显示

### ISSUE THREAD

**Issue by vinwang** [howie6879/owllook#20]

**Comment by vinwang** [comment]
[https://www.owllook.net/chapter?url=https://www.biquta.com/1_1733/&novels_name=%E6%AD%A3%E9%81%93%E6%BD%9C%E9%BE%99](url) 比如这个

**Comment by howie6879** [comment]
你点进去看小说章节就好了。。。

**Comment by vinwang** [comment]
2018-03-12 18:09:27,018 ERROR root(56) | Unexpected error with RedisCache (localhost:6379)

AttributeError: 'RedisConnection' object has no attribute 'exists'

你好，这是什么原因啊

**Comment by howie6879** [comment]
估计版本不对

**Comment by vinwang** [comment]
python  3.6
redis 2.10.6

**Comment by howie6879** [comment]
指的是第三方包的版本

**Comment by vinwang** [comment]
![1520911323937](https://user-images.githubusercontent.com/1687353/37320892-dda1a06a-26b0-11e8-9a03-a2d7e3753635.jpg)

**Comment by howie6879** [comment]
对  按照这个版本就行了

**Comment by vinwang** [comment]
就是按照这个版本安装的，然后出现redis那个错误

**Comment by howie6879** [comment]
1.你先看看你实际的第三方包是否和这个一样，出现这个错误应该是版本原因
2.找不出的话，就用docker
