### ISSUE TITLE
AttributeError: type object 'Config' has no attribute 'MONGODB'

### ISSUE THREAD

**Issue by joytianya** [howie6879/owllook#21]
在运行爬虫python3 ../../owllook/spiders/spider_console.py 时会报如题的错误，这是什么原因

**Comment by howie6879** [comment]
你好 请看下readme的FAQ

**Comment by joytianya** [comment]
os.environ['MODE'] = 'PRO' 这段代码也请注释掉 注释掉了，还是报这个错误

**Comment by howie6879** [comment]
里面的其他文件的这段也要注释掉
