### ISSUE TITLE
是不是只能bind loopback接口

### ISSUE THREAD

**Issue by PaulPaulYang** [howie6879/owllook#22]
我如果设置在物理接口上，直接就是一个302重定向，是不是只能工作在本地的loopback接口呢？

谢谢

**Comment by howie6879** [comment]
https://github.com/howie6879/owllook/blob/master/owllook/server.py
你直接将58到67行 注释掉就好了

**Comment by PaulPaulYang** [comment]
谢谢您的及时回复，我在config.py的host中增加了对应的地址解决了问题，多谢您，另外阅读排版在电脑上很合适，但是在ipad上看感觉实际有效阅读空间比较窄，这个应该在哪儿调整呢？ 多谢！

**Comment by howie6879** [comment]
不客气 ipad下面只需要修改css就好了 https://github.com/howie6879/owllook/blob/master/owllook/static/novels/css/content.css

**Comment by PaulPaulYang** [comment]
多谢多谢，我去试一试哈。
