### ISSUE TITLE
pip install -r requirements.txt 报错

### ISSUE THREAD

**Issue by lonlonelong** [howie6879/owllook#23]
![image](https://user-images.githubusercontent.com/19237141/38192561-0b4c9778-36a0-11e8-9f5e-d82cecfe29f0.png)

**Comment by howie6879** [comment]
你先切换到国内源 比如清华源 再安装看看

**Comment by lonlonelong** [comment]
我的py有两个版本。默认是2.7，还有个3.6的

**Comment by howie6879** [comment]
你需要用py3.6的

**Comment by lonlonelong** [comment]
这个怎么用啊。

**Comment by lonlonelong** [comment]
我的qq：3111288391。大神指点一下吧

**Comment by howie6879** [comment]
直接切换到3.6就好了 谷歌下你就会了。很简单

**Comment by lonlonelong** [comment]
终于好了，感谢大神
