### ISSUE TITLE
python server.py该步骤后出现如图所示，该如何继续呢？

### ISSUE THREAD

**Issue by iWvel** [howie6879/owllook#24]
![image](https://user-images.githubusercontent.com/22401759/38472568-52edb2d8-3bb4-11e8-80a7-1291802fbedb.png)

**Comment by howie6879** [comment]
你指的继续是干嘛 服务这不是已经启动了么

**Comment by iWvel** [comment]
访问是403错误。是我访问的不对么？

**Comment by howie6879** [comment]
你访问什么？具体错误日志是？

**Comment by iWvel** [comment]
![image](https://user-images.githubusercontent.com/22401759/38474557-c80bd45a-3bd2-11e8-8f2a-3aa876f086c3.png)
部署好后，如何访问到主页呢?

**Comment by howie6879** [comment]
127.0.0.1:8001

**Comment by iWvel** [comment]
Centos7 niginx1.8
部署后，设置伪静态。
location / {
            proxy_pass http://127.0.0.1:8001;
        }
有如下问题
![image](https://user-images.githubusercontent.com/22401759/38497168-c63b7634-3c32-11e8-9bba-905ef7601c7d.png)
显示不正常。
![image](https://user-images.githubusercontent.com/22401759/38497205-ddf3e8d8-3c32-11e8-877f-9748624181d8.png)
搜索结果点击章节后，页面404。
能否解答下呢？打扰了：）

**Comment by howie6879** [comment]
不用nginx 有问题么？

**Comment by howie6879** [comment]
我意思是直接启动有没有问题~
