### ISSUE TITLE
安装成功，服务也正常启动 ..但是无法访问 

### ISSUE THREAD

**Issue by Sabirjan** [howie6879/owllook#25]
![image](https://user-images.githubusercontent.com/7404699/38927297-ddf977d8-4337-11e8-8fb0-89bbd32ceb46.png)

无法访问 ，阿里云的防火墙里面设置了端口，不知道怎么绑定IP
直接用IP：端口 访问，无法访问....

**Comment by Sabirjan** [comment]
![image](https://user-images.githubusercontent.com/7404699/38927417-421861fc-4338-11e8-8c4b-a65055f2a844.png)
都安装成功的

**Comment by howie6879** [comment]
改为0.0.0.0

**Comment by howie6879** [comment]
不是很明白你表述的意思
