### ISSUE TITLE
推荐源biqugexsw没有解析成功

### ISSUE THREAD

**Issue by tidyx** [howie6879/owllook#33]
推荐源biqugexsw没有解析成功
https://www.owllook.net/chapter?url=http://www.biqugexsw.com/1_1020/&novels_name=%E4%B8%87%E7%95%8C%E5%A4%A9%E5%B0%8A

**Comment by howie6879** [comment]
https://www.owllook.net/chapter?url=https://www.bqg5200.com/book/26410/&novels_name=%E7%A5%9E%E5%B7%A5

**Comment by howie6879** [comment]
已解决
