### ISSUE TITLE
搜索的关键词需要替换下

### ISSUE THREAD

**Issue by rain10154** [howie6879/owllook#43]
直接替换成书名+全文阅读就可以，这样对小说和图书都有效果，不然太过侧重小说

**Comment by howie6879** [comment]
本来就是偏向小说 有需求你可以fork自己改哈

**Comment by rain10154** [comment]
哈哈，我就是觉得只是小说太可惜了，其实可以兼顾的

**Comment by howie6879** [comment]
可以的 你只要在检索的时候再加空格 加关键词也行
