### ISSUE TITLE
ModuleNotFoundError: No module named 'aiocache.utils

### ISSUE THREAD

**Issue by yuhanghate** [howie6879/owllook#47]
你好,我很高兴可以找到类似的项目.
我编译时出现了问题:
/Users/yuhang/Android/python/owllook-master/venv/bin/python /Users/yuhang/Android/python/owllook-master/owllook/server.py
msgpack not installed, MsgPackSerializer unavailable
[2018-11-05 17:14:14,818] 37407-INFO __init__::load_config():l24: owllook 启动模式：DEV
Traceback (most recent call last):
  File "/Users/yuhang/Android/python/owllook-master/owllook/server.py", line 12, in <module>
    from owllook.views import admin_bp, api_bp, except_bp, md_bp, novels_bp, operate_bp
  File "/Users/yuhang/Android/python/owllook-master/owllook/views/__init__.py", line 1, in <module>
    from .admin_blueprint import admin_bp
  File "/Users/yuhang/Android/python/owllook-master/owllook/views/admin_blueprint.py", line 9, in <module>
    from owllook.fetcher.cache import get_the_latest_chapter
  File "/Users/yuhang/Android/python/owllook-master/owllook/fetcher/cache.py", line 16, in <module>
    from owllook.fetcher.decorators import cached
  File "/Users/yuhang/Android/python/owllook-master/owllook/fetcher/decorators.py", line 10, in <module>
    from aiocache.utils import get_args_dict, get_cache
ModuleNotFoundError: No module named 'aiocache.utils'

进入到 decorators.py文件发现有问题文件过时了

from aiocache.log import logger
from aiocache.utils import get_args_dict, get_cache

导入文件的时候 **logger** **get_args_dict,** **get_cache** 这两个方法没有

目前最新的方法是封装成了类.
我不知道该怎么解决.可以帮助我吗

最新的:
https://github.com/argaen/aiocache/blob/634348f40ce8caa01c7c35010acf32d8c3e17ba6/aiocache/decorators.py

**Comment by howie6879** [comment]
请使用pipenv安装 那里面固定了版本

yuhanghate <notifications@github.com> 于2018年11月5日周一 下午5:36写道：

**Comment by yuhanghate** [comment]
好快,谢谢你的回答.我使用pipenv试一下.我目前使用的是charm自带的env

**Comment by yuhanghate** [comment]
你好,docker可以下载下来.但我是想在pycharm上跑工程.除了用老版本的环境或者aiocache更新到最新的以外.还有其他的好主意吗?
我需要帮助

**Comment by howie6879** [comment]
不懂你的意思 你有遇到什么问题么？

**Comment by yuhanghate** [comment]
项目工程跑不起来,decorators.py文件用的是老的api方法.
我的开发工具使用的是pycharm
我想在开发工具上把demo跑起来

**Comment by howie6879** [comment]
我想你比较少接触python吧 这个和你说的问题没有丝毫的关系

**Comment by yuhanghate** [comment]
是的,我主要写koltin/java. python用得比较少
导入项目的时候提示缺少### aiocache模块,我使用pip3:
`pip3 install aiocache`
进入安装,版本是0.10.0.
提示我以下包已经没有了
```
from aiocache.log import logger
from aiocache.utils import get_args_dict, get_cache
```
我查看aiocache项目源码发现**log**和**utils**已经不见了.使用了新的方法代替

我不知道该怎么办,我尝试使用最新的aiocache里面的demo.
通过注解的形式

**Comment by howie6879** [comment]
pipenv用法 了解一下 pipenv生成的环境 导入到pycharm就行

**Comment by howie6879** [comment]
简单粗暴点 pip3 install aiocache==0.3.2 也行

**Comment by yuhanghate** [comment]
好的,非常感谢
我打算使用:
`pip3 install aiocache==0.3.2`

我先把demo跑起来.
我准备扩展一个`android`平台的app,作为一个补充

我在京东双十一买了kindle p4 ,
打算使用他来看小说,如果以后扩展kinkle.
我想这是个非常好的主意
支持作者
