### ISSUE TITLE
"我的书架" 模块点不进去了。。挂掉了

### ISSUE THREAD

**Issue by wangyingbo** [howie6879/owllook#61]

**Comment by howie6879** [comment]
我这边没问题 你再试试？

**Comment by wangyingbo** [comment]
@howie6879 刚截了个图，你看下哈
https://raw.githubusercontent.com/wangyingbo/PrivateImages/master/2019/owllook_gif.gif
https://raw.githubusercontent.com/wangyingbo/PrivateImages/master/2019/owllook_resonse_error.png

**Comment by wangyingbo** [comment]
<img width="1289" alt="owllook_resonse_error" src="https://user-images.githubusercontent.com/12741589/52770859-3c23e800-306f-11e9-8ab6-070673799ae9.png">

**Comment by howie6879** [comment]
![image](https://user-images.githubusercontent.com/17047388/52776950-b2c7e200-307d-11e9-9a04-430a5e465089.png)
你书架上会有很多书么？

**Comment by wangyingbo** [comment]
不多吧？一二十本的样子

**Comment by howie6879** [comment]
如果可以的话 你先把账号密码发我邮箱 我测试看看

**Comment by wangyingbo** [comment]
@howie6879 不好意思刚看到，账号和密码已经发到你的邮箱`xiaozizayang@gmail.com`里了
