### ISSUE TITLE
关于Sanic坑不坑

### ISSUE THREAD

**Issue by TonyK-T** [howie6879/owllook#71]
1、Sanic性能咋样？真比Tornado好么
2、Sanic碰到那些巨坑？

**Comment by howie6879** [comment]
1.还好 Tornado没用过生产，性能比falsk在同等条件快个1.5
2.有过一次内存泄漏的坑

**Comment by TonyK-T** [comment]
1.Tornado vs Flask+gunicorn  vs Sanic,    性能和稳定性有测试过么？ 哪个偏强点？

**Comment by howie6879** [comment]
没用过tornado
flask 和 sanic看前面回答

stringk <notifications@github.com> 于2019年9月5日周四 上午10:24写道：

**Comment by TonyK-T** [comment]
1.Tornado vs Flask+gunicorn vs Sanic, 性能和稳定性有测试过么？ 哪个偏强点？
2. Sanic 拓展开发感觉咋样、能方便快速开发用于生产吗？

**Comment by howie6879** [comment]
> 2. Sanic 拓展开发感觉咋样、能方便快速开发用于生产吗？

自用还算方便
