### ISSUE TITLE
按照安装教程pipenv install 安装失败，小白一枚，麻烦看看

### ISSUE THREAD

**Issue by jason163** [howie6879/owllook#81]
虚拟机VMware + OS: CentOS8
一步步按照安装教程来进行，日志如下：
![image](https://user-images.githubusercontent.com/3665287/76587705-c020fb80-651f-11ea-8de5-1a3726b230e3.png)

小白一枚，麻烦看看

**Comment by howie6879** [comment]
应该是你没有安装一些基础包，具体你可以谷歌一下

**Comment by jason163** [comment]
> 应该是你没有安装一些基础包，具体你可以谷歌一下

搞定，centos8没有gcc的编译器相关的开发工具包，安装上就可以了
