### ISSUE TITLE
如何调试源码

### ISSUE THREAD

**Issue by jason163** [howie6879/owllook#82]
请问楼主是用什么IDE写的代码，怎么调试源码

我用的VSCODE，调试时候没有gunicorn的选项，求指导

**Comment by howie6879** [comment]
我用pycharm你可以试试

**Comment by jason163** [comment]
@howie6879 新加sogou抓取，但不知道怎么调试，提示pycharm no module named 'owllook'。小白一枚，帮帮忙。
![image](https://user-images.githubusercontent.com/3665287/77133051-a130e500-6a9c-11ea-8f5b-830c720e7afe.png)

**Comment by jason163** [comment]
done
