### ISSUE TITLE
docker打包镜像出错

### ISSUE THREAD

**Issue by codemonkey92868** [howie6879/owllook#84]
依据readme.md 为了解决
AttributeError: type object 'Config' has no attribute 'MONGODB'
选择配置数据库设置，方案二
执行
docker build -t howie6879/owllook . 报错
出现如下错误
查找索引：http://mirrors.aliyun.com/pypi/simple/
警告：在“newconnectonerror（'<pip.\u vendor.urllib3.connection.HTTPConnection object at 0x7f9d12cf4668>：未能建立新连接：[Errno-3]名称解析中的临时失败'，）”：pypi/simple/pipenv断开连接后重试（重试（总计=4，连接=None，读取=None，重定向=None，状态=None）/
下面是截图
![00](https://user-images.githubusercontent.com/61646468/78638355-b8feca80-78de-11ea-8e2b-6adf8de231a3.png)

打开查找索引：http://mirrors.aliyun.com/pypi查看，发现没有simple目录，只有packages/；web/;generation；status；四个

想问解决这个问题，是不是要修改docker里面的某个网络链接或者配置文件?
如果是怎么修改呢？
如果不是请大神帮忙看看
谢谢，谢谢，谢谢！

**Comment by livuswang** [comment]
修改文件Dockerfile,把里面的http://mirrors.aliyun.com/pypi/simple/ 改成其他pypi源,比如 https://pypi.doubanio.com/simple/ 或则 https://pypi.tuna.tsinghua.edu.cn/simple/
试试吧

**Comment by codemonkey92868** [comment]
改过之后好了，谢谢，谢谢，谢谢！
但那个它运行之后出现别的错误了可以稍微看下嘛....
![image](https://user-images.githubusercontent.com/61646468/78644737-ee101a80-78e8-11ea-9593-fea539844089.png)
说让提供一个安装要求...

**Comment by livuswang** [comment]
Dockerfile这么改 试试

# 基于python3.6镜像来构建owllook镜像
FROM python:3.6
MAINTAINER howie6879 <howie6879@gmail.com>
ENV TIME_ZONE=Asia/Shanghai
RUN echo "${TIME_ZONE}" > /etc/timezone \
    && ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime
ADD . /owllook
WORKDIR /owllook
RUN pip install --no-cache-dir --trusted-host pypi.doubanio.com -i https://pypi.doubanio.com/simple/ pipenv
RUN pipenv install --skip-lock
RUN find . -name "*.pyc" -delete

**Comment by codemonkey92868** [comment]
![image](https://user-images.githubusercontent.com/61646468/78651349-cb82ff00-78f2-11ea-8b76-0c1eedb1682a.png)
还是报错，，，，
![image](https://user-images.githubusercontent.com/61646468/78651463-f2413580-78f2-11ea-8484-23ca80331cba.png)

**Comment by livuswang** [comment]
我是原版安装的 不是用docker安装,待我去虚拟机测试下 再来告诉你

**Comment by codemonkey92868** [comment]
......可能我前面装错了吧，我在装一遍，，，，，
那个可以加下联系方式嘛，嘿嘿
15236464797微信，膜拜大神

**Comment by codemonkey92868** [comment]
请问一下，什么是原版安装，是按照下图这样吗
![image](https://user-images.githubusercontent.com/61646468/78666690-4c99c080-790a-11ea-958c-bec2285ee2d2.png)

docker安装是虚拟机上安装过必要软件之后，直接用docker下载运行环吗？

**Comment by livuswang** [comment]
你加我QQ 305966280 说吧

**Comment by codemonkey92868** [comment]
师傅真的很好，大牛，大牛
