### ISSUE TITLE
反馈区：欢迎提意见

### ISSUE THREAD

**Issue by howie6879** [howie6879/owllook#9]
欢迎提建议，为了使项目更好，谢谢。
这里提供多种解决方案：https://github.com/owllook-for-you

**Comment by zhang0peter** [comment]
没问题，感谢你的网站。

**Comment by howie6879** [comment]
@zhang0peter  :grinning:

**Comment by yangfan920215** [comment]
很不错的站点，对我学习python很有帮助，感谢

**Comment by jiangxin123** [comment]
安装包报错：uvloop does not support Windows at the moment

**Comment by howie6879** [comment]
@jiangxin123 

SANIC_NO_UVLOOP=true SANIC_NO_UJSON=true pip install sanic 

https://github.com/channelcat/sanic

**Comment by cjwddtc** [comment]
网站部署到服务器上面之后和https://www.owllook.net/上面的不一样
举个例子搜索超级修真保镖搜到的源不一样而且会少很多如何解决

**Comment by howie6879** [comment]
你好 @cjwddtc 
你可以去掉缓存重新搜索一次 因为每次搜索结果会变 或者你也可以直接换搜索源 360的源不错

**Comment by cjwddtc** [comment]
如何清空缓存@howie6869

**Comment by cjwddtc** [comment]
如何清空缓存 @howie6879

**Comment by howie6879** [comment]
@cjwddtc 去redis清除

**Comment by cjwddtc** [comment]
我阅读了一下源代码，为什么不把4个搜索引擎的结果合并到一起呢？  @howie6879

**Comment by howie6879** [comment]
@cjwddtc 没必要 一个就够了

**Comment by wxlost** [comment]
首页搜索小说正常.点排行榜没有数据.....请问在哪里看错误日志

**Comment by howie6879** [comment]
@wxlost 需要运行owllook/spiders/spider_console.py，目前代码中是设定60分钟运行一次，运行的时候请酌情更改

**Comment by wxlost** [comment]
[root@xenserver cloudreve]# cd /home/owllook/owllook/spiders/
[root@xenserver spiders]# python3 spider_console.py
Traceback (most recent call last):
  File "spider_console.py", line 10, in <module>
    from owllook.spiders import QidianRankingSpider, BdNovelSpider
  File "../../owllook/spiders/__init__.py", line 1, in <module>
    from .qidian_ranking import QidianRankingSpider
  File "../../owllook/spiders/qidian_ranking.py", line 9, in <module>
    from owllook.database.mongodb import MotorBaseOld
  File "../../owllook/database/mongodb/__init__.py", line 1, in <module>
    from .motorbase import MotorBase, MotorBaseOld
  File "../../owllook/database/mongodb/motorbase.py", line 8, in <module>
    @singleton
  File "../../owllook/database/mongodb/motorbase.py", line 16, in MotorBase
    MONGODB = CONFIG.MONGODB
AttributeError: type object 'Config' has no attribute 'MONGODB'

**Comment by wxlost** [comment]
@howie6879 直接启动报错.MONGODB要强制设置用户名和密码吗?

**Comment by BlueRagdoll** [comment]
@wxlost 我也是这个问题，请问你的解决了吗？

**Comment by howie6879** [comment]
os.environ['MODE'] = 'PRO' 这段代码请先注释掉

**Comment by BlueRagdoll** [comment]
@howie6879 谢谢你了，刚看到你发的邮件，抱歉。

**Comment by 317482454** [comment]
打扰了问个问题：
网站能正常运行，但是无法登陆，也不报错
我是否需要设置这里：
MONGODB = dict(
        MONGO_HOST=os.getenv('MONGO_HOST', ""),
        MONGO_PORT=os.getenv('MONGO_PORT', 27017),
        MONGO_USERNAME=os.getenv('MONGO_USERNAME', ""),
        MONGO_PASSWORD=os.getenv('MONGO_PASSWORD', ""),
        DATABASE='owllook',
    )

**Comment by howie6879** [comment]
@317482454 注册成功了么？

**Comment by 317482454** [comment]
@howie6879 注册直接跳转到主页,控制台输出：
2018-06-15 01:36:56,095 INFO root(55) | user ip is: None

**Comment by howie6879** [comment]
@317482454 config文件 VAL_HOST = os.getenv('VAL_HOST', 'true') 改为VAL_HOST = 0 再试试

**Comment by 317482454** [comment]
@howie6879 排行榜出现test，但是还无法登陆跟注册，会不会是因为没连接上mongo？

如果连接不上mongo会出现什么错误？

但是我去mongo里面看到了创建了owllook

**Comment by howie6879** [comment]
@317482454 
1.是否注册成功？注册成功mogo有user表
2.无法登陆报什么错？
无法描述可截图

**Comment by 317482454** [comment]
1.注册成功了，user表有数据
![image](https://user-images.githubusercontent.com/16585053/41461703-01de08ae-70c3-11e8-8299-d301a0f8378b.png)

2.没有报错，就是没反应

查看了login返回：status:0

![image](https://user-images.githubusercontent.com/16585053/41461751-31177740-70c3-11e8-8cc3-db67db07bbe0.png)

**Comment by howie6879** [comment]
![image](https://user-images.githubusercontent.com/17047388/41461998-fc1d2f66-70c3-11e8-8a95-00bda56292d0.png)
这说明没获取到你的user以及pass参数 你看看你改动什么了吧，什么class id名字

**Comment by 317482454** [comment]
@howie6879 我想我知道我那错了，登陆跳转以后，重定向就丢失了用户信息，是因为我加上了域名的问题？但是我不知道在哪修改。

**Comment by zhuhangyu** [comment]
我用docker运行的，为啥访问8001端口，就直接被302跳转到你的官网了呢?

**Comment by howie6879** [comment]
@zhuhangyu 在.env 加一行 VAL_HOST=0

**Comment by howie6879** [comment]
@zhuhangyu docker logs [your docker id]

**Comment by zhuhangyu** [comment]
2018-07-25 15:38:19,642 ERROR aiocache.log(126) | Unexpected error with RedisCache (172.17.0.1:6379)
Traceback (most recent call last):
  File "/opt/owllook/fetcher/decorators.py", line 122, in wrapper
    if await cache_instance.exists(cache_key):
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/aiocache/cache.py", line 41, in _enabled
    return await fn(*args, **kwargs)
  File "/root/.local/share/virtualenvs/opt-zvmYt2-H/lib/python3.6/site-packages/aiocache/cache.py", line 31, in _timeout
    return await asyncio.wait_for(fn(self, *args, **kwargs), self.timeout)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

浏览器一直在转圈

**Comment by howie6879** [comment]
@zhuhangyu mongodb 以及redis需要外网访问，你这个连接上了么？

**Comment by howie6879** [comment]
@zhang0peter 应该是密码错了 你看看哪里输错没

**Comment by zhuhangyu** [comment]
我把REDIS_PASSWORD='eNIuP'改为REDIS_PASSWORD=eNIuP
去掉单引号，redis就不报错

但是mongo去掉单引号，仍然报错

**Comment by zhuhangyu** [comment]
# mongo -u root -p --authenticationDatabase admin --host 172.17.0.1
MongoDB shell version: 3.2.20
Enter password: 
connecting to: 172.17.0.1:27017/test
> 
> 
> 
> use admin
switched to db admin
> show dbs
admin  0.000GB
local  0.000GB
> 


mongo的用户名root，用命令行可以登录的

**Comment by howie6879** [comment]
@zhuhangyu 
```
MONGODB = dict(
        MONGO_HOST=os.getenv('MONGO_HOST', ""),
        MONGO_PORT=os.getenv('MONGO_PORT', 27017),
        MONGO_USERNAME=os.getenv('MONGO_USERNAME', ""),
        MONGO_PASSWORD=os.getenv('MONGO_PASSWORD', ""),
        DATABASE='owllook',
    )
```
你可以本地写个操作mongo的代码，用你的用户名密码连接操作集合owllook，连接代码可参考database/mongodb

**Comment by zhuhangyu** [comment]
搞定了
1、dev_owllook.env里面的值不能用单引号括起来
2、之前用root账号，只能对admin数据库有权限，后来我另建了一个账号

**Comment by howie6879** [comment]
@zhuhangyu 玩得愉快

**Comment by zhuhangyu** [comment]
自己喜欢看书，没广告，舒服了。谢谢

**Comment by zhuhangyu** [comment]
@howie6879 再请问，我点搜索排行，不管是本站的榜单，还是起点或纵横的榜单，都是空的，没有数据。我看你的官网是有数据的。

**Comment by howie6879** [comment]
@zhuhangyu 看readme

**Comment by zhuhangyu** [comment]
看了的
root@344e6905ac50:/opt/owllook/spiders# pipenv shell
Launching subshell in virtual environment…
root@344e6905ac50:/opt#  . /root/.local/share/virtualenvs/opt-zvmYt2-H/bin/activate
(opt-zvmYt2-H) root@344e6905ac50:/opt# cd owllook/spiders/
(opt-zvmYt2-H) root@344e6905ac50:/opt/owllook/spiders# python spider_console.py 
[2018-07-26 09:38:51,634] 218-INFO __init__::load_config():l27: owllook 启动模式：DEV

没报错，但还没数据

**Comment by zhang0peter** [comment]
大佬，你能不能用docker-compose，然后把mongdb和redis都放在docker中启动，这样我们就可以直接用了

**Comment by hsyysy** [comment]
我有一个想法，仅供参考。
目前的分类机制是对于一个书名，有不同的提供网站。
但实际上每本书都有一个或几个官方发布网站，网站可以抓取到书的目录和每一章的前两段，那么
1.通过网友的共同劳动，像Wiki一样建立一个书名与官方发布页面地址的映射目录。
2.抓取官方发布的目录建立书籍的目录，然后通过每章前两段内容与其他网站内容的比对抽取完整章节。
而不用显示多个源。

可能存在以下问题
1.抓取官方目录和前两段可能涉嫌侵权。
2.文字对比可能正确率低。

**Comment by howie6879** [comment]
@hsyysy 这样做我觉得还不如目前方便，而且目前还不用抓取章节内容，目前以搜索为驱动至少不会侵权

**Comment by DLDLDLDLDLDL** [comment]
你好，我是一名在校大学生，我想学python web 开发，请问有什么推荐的书吗

**Comment by bosen365** [comment]
> @zhuhangyu 在.env 加一行 VAL_HOST=0

为何我添加了这一行，还是一样的302跳转呢，当前最新的代码编译运行的

**Comment by pppploi8** [comment]
bootcss的cdn地址已经更换了，作者不考虑更新下么，没部署直接用owllook页面样式都挂了好几天了

**Comment by howie6879** [comment]
抱歉 出去旅游了

pppploi8 <notifications@github.com>于2018年10月3日 周三下午3:01写道：

**Comment by 892947707** [comment]
首先，非常感谢你的辛苦和分享，其次，有没有更简单的安装方法，光是配置系统环境对我这个小白来说就已经很困难了，到了安装的时候卡住已经没办法了，好痛苦啊

**Comment by zhuhangyu** [comment]
> @zhuhangyu
> ![image](https://user-images.githubusercontent.com/11971273/48334994-5d9fbd00-e697-11e8-85df-acf860795bd4.png) 就是这个问题 排行榜没有数据

我没解决。不知道是不是查询的数据不够多。反正我就是自己看书使用的，无所谓了。

**Comment by zzslion** [comment]
> > @zhuhangyu
> > ![image](https://user-images.githubusercontent.com/11971273/48334994-5d9fbd00-e697-11e8-85df-acf860795bd4.png) 就是这个问题 排行榜没有数据
> 
> 我没解决。不知道是不是查询的数据不够多。反正我就是自己看书使用的，无所谓了。

我也是这个问题同求怎么解决

**Comment by terrorist002** [comment]
请问ssl证书如何安装呢？

**Comment by terrorist002** [comment]
域名需要绑定吗？安装好了后，爬虫也能工作了，就是网站打不开。还是我没设置？

**Comment by tianminglei** [comment]
没有找回密码啊

**Comment by howie6879** [comment]
> 没有找回密码啊

用户名发我 可以帮你重置一个默认密码你自己再改

**Comment by tianminglei** [comment]
> > 没有找回密码啊
> 
> 用户名发我 可以帮你重置一个默认密码你自己再改

shmilyfox190@163.com

**Comment by howie6879** [comment]
> > > 没有找回密码啊
> > 
> > 
> > 用户名发我 可以帮你重置一个默认密码你自己再改
> 
> [shmilyfox190@163.com](mailto:shmilyfox190@163.com)

用户名：田大磊
密码：demo

**Comment by GEORGE6701** [comment]
多次出现
Internal Server Error
The server encountered an internal error and cannot complete your request.

**Comment by fastbucket** [comment]
你好这个可以用django重写吗？

**Comment by x-haose** [comment]
报这个错咋办，网页返回500  

File "/root/.local/share/virtualenvs/owllook-kjRL-ddR/lib/python3.6/site-packages/sanic_session/redis_session_interface.py", line 70, in open
    request['session'] = session_dict
TypeError: 'Request' object does not support item assignment
[2020-05-29 01:54:26 +0800] - (sanic.access)[INFO][127.0.0.1:34992]: GET http://book.haose.one/  500 250

**Comment by qiansandjd** [comment]
之前能搜到的小说，后来一搜索都成了，让我反馈给本网站，现在搜啥都是让我反馈
