### ISSUE TITLE
哪里可以关闭直接跳转第三方网站啊

### ISSUE THREAD

**Issue by tidyx** [howie6879/owllook#90]
请问哪里可以关闭直接跳转第三方网站啊，因为这个跳转，被主机关闭了网络，[https://www.lolsodu.com/chapter?url=https://u.to/i3mdGA&novels_name=ixsx6uycjhhkp2]

**Comment by livuswang** [comment]
我和你一样,因为这个跳转,主机被封了.

**Comment by livuswang** [comment]
搜索novels_blueprint.py里的return redirect(url),把return redirect(url)修改成return text('解析失败'),就不会跳转第三方网站了,我是这么修改的,你也可以按照你自己的意思修改.
